version: "3.8"
services:
    mongodb:
        image : mongo:4.4
        container_name: mongodb
        environment:
        - PUID=1000
        - PGID=1000
        volumes:
        - /Users/bradybess/Documents/Personal/MiscCoding/Instagram/GAA/db:/data/db
        ports:
        - 27017:27017
        restart: unless-stopped